### ISSUE TITLE
how to use pre-trained word embedding？

### ISSUE THREAD

**Issue by NonvolatileMemory** [SherlockLiao/mxnet-gluon-tutorial#2]
your code is so awesome.
But if I want to use pre-trained embedding matrix to initialize gluon.nn.Embedding(),what should I do?

**Comment by L1aoXingyu** [comment]
you can define a initial word embedding and then set the weight by yourself, such as 
```
x = nn.Embedding(3, 5)
x.initialize()
x.weight.set_data(nd.ones(shape=(3, 5))
print(x.weight.data())
```

**Comment by NonvolatileMemory** [comment]
yes,I got that.very thanks
https://zhuanlan.zhihu.com/p/31664048

**Comment by NonvolatileMemory** [comment]
seems this method is wrong when use gpu?
https://github.com/apache/incubator-mxnet/issues/8963

**Comment by NonvolatileMemory** [comment]
figure out ,nd.ones() must init on gpu
